### PR TITLE
Update to make plugin work with GoCD 17.1 and above

### PR DESCRIPTION
**Pull request by arvindsv**
Using the [plugin shim](https://github.com/gocd-contrib/gocd-package-material-plugin-shim) to upgrade this plugin, so that it works with 17.1. Without this change, this plugin will stop working from GoCD 17.1 onwards.

### CODE REVIEW

**Comment by arvindsv** [comment]
Configuration used to check this:

```
<repository id="2d154e44-d917-4b4d-b1e5-5eaaa361791a" name="deb">
  <pluginConfiguration id="deb" version="1" />
  <configuration>
    <property>
      <key>REPO_URL</key>
      <value>http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/</value>
    </property>
  </configuration>
  <packages>
    <package id="f2035430-9ccc-42eb-b353-a6667265cb12" name="myname">
      <configuration>
        <property>
          <key>PACKAGE_NAME</key>
          <value>openssl</value>
        </property>
      </configuration>
    </package>
  </packages>
</repository>
```

**Comment by ketan** [comment]
Bump version and make a release?

**Comment by arvindsv** [comment]
Yes. If you can, please do. If not, I'll do it tomorrow.

**Comment by arvindsv** [comment]
@ketan - Can you take a look at the other PR: https://github.com/gocd-contrib/deb-repo-query/pull/7 - because I want to "release" that first and then use that here.

**Pull request merged**
